version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt
    - method: setuptools
      path: .

before_install:
  - python3 -m ipykernel install --user

submodules:
  include: all

