version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - before: 
        - python3 -m ipykernel install --user
    - requirements: requirements.txt
    - method: setuptools
      path: .

submodules:
  include: all

