version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
      - pwd
      - ./radiocalibrationtoolkit/doc/examples/build_example_datasets.sh

python:
  install:
    - requirements: requirements.txt
    - method: setuptools
      path: .

submodules:
  include: all


formats:
  - pdf
  - epub
