version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt
    - method: setuptools
      path: .

submodules:
  include: all


formats:
  - pdf
  - epub
